- name: Update Repository cache
  shell: apt-get update
  tags:
    - packages

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm
    - yarnpkg
    - python3-pip
    - postgresql
    - uwsgi
    - uwsgi-plugin-python3
    - nginx
    - letsencrypt
  tags:
    - packages

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - "asgiref==3.5.2"
    - "Django==4.1.13"
    - "django-yarnpkg==6.1.0"
    - "gunicorn==20.1.0"
    - "psycopg2-binary==2.9.9"
    - "PyYAML==6.0"
    - "six==1.16.0"
    - "sqlparse==0.4.4"
  tags:
    - packages

