- name: Allow port 22 (ssh)
  ufw:
    rule: allow
    port: 22
    proto: tcp
  tags:
    - firewall

- name: Allow port 80 (http)
  ufw:
    rule: allow
    port: 80
    proto: tcp
  tags:
    - firewall

- name: Allow port 443 (https)
  ufw:
    rule: allow
    port: 443
    proto: tcp
  tags:
    - firewall

- name: Activate firewall
  ufw:
    state: enabled
    logging: on
  tags:
    - firewall
