- name: Create tealdb directory
  file:
    path: "{{ base_dir }}"
    state: directory
  tags:
    - app_setup

- name: Git checkout of tealdb code
  git:
    repo: "https://{{ github_username }}:{{ github_token }}@github.com/tangledhelix/tealdb.git"
    dest: "{{ base_dir }}"
    version: "{{ tealdb_git_branch }}"
  tags:
    - app_setup

- name: Application secrets module
  template:
    src: secrets.py.j2
    dest: "{{ base_dir }}/turnitteal/secrets.py"
    mode: 0644
    owner: root
    group: root
  tags:
    - app_setup

- name: Django migration
  shell: python3 manage.py migrate
  args:
    chdir: "{{ base_dir }}"
  tags:
    - app_setup

- name: Django yarn install
  shell: python3 manage.py yarn install
  args:
    chdir: "{{ base_dir }}"
  tags:
    - app_setup

- name: Django collect static assets
  shell: python3 manage.py collectstatic --no-input
  args:
    chdir: "{{ base_dir }}"
  tags:
    - app_setup
